#beach
image bg_sea_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/海(日中).png"#过场用
image bg_sea_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/海(夕方).png"#过场用
image bg_sea_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/海(夜).png"#过场用
image bg_beach_1_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach1(noon).png"
image bg_beach_1_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach1(sunset).png"
image bg_beach_1_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach1(night).png"
image bg_beach_2_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach2(noon).png"
image bg_beach_2_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach2(sunset).png"
image bg_beach_2_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach2(night).png"
image bg_beach_3_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach3(noon).png"
image bg_beach_3_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach3(sunset).png"
image bg_beach_3_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach3(night).png"
image bg_beach_noon_second = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach_noon(second).png"#第一次后解锁
image bg_beach_sunset_second = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach_sunset(second).png"
image bg_beach_park_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach_park(noon).png"
image bg_beach_park_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach_park(sunset).png"
image bg_beach_park_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach_park(night).png"
image bg_beach_station_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach_station(noon).png"
image bg_beach_station_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach_station(sunset).png"
image bg_beach_station_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/beach_station(night).png"
image bg_seaside_bench_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/seaside_bench(noon).png"
image bg_seaside_bench_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/seaside_bench(sunset).png"
image bg_seaside_bench_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/seaside_bench(night).png"
image bg_seaside_sidewalk_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/seaside_sidewalk(noon).png"
image bg_seaside_sidewalk_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/seaside_sidewalk(sunset).png"
image bg_seaside_sidewalk_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/seaside_sidewalk(night).png"
image bg_sea_seawalk_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/sea_延道(noon).png"#朝亭子走的路
image bg_sea_seawalk_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/sea_延道(sunset).png"
image bg_sea_seawalk_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/sea_延道(night).png"
image bg_sea_pavilion_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/sea_liangting(noon).png"#休息亭子早
image bg_sea_pavilion_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/sea_liangting(sunset).png"#日落
image bg_sea_pavilion_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/sea_liangting(night).png"

# add
image bg_Meoto_Rocks_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Meoto_Rocks_0.png"#夫妇岩
image bg_Meoto_Rocks_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Meoto_Rocks_2.png"
image bg_Meoto_Rocks_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Meoto_Rocks_1.png"
image bg_Mountain_Road_Bridge_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Mountain_Road_Bridge(noon).png"#山道桥
image bg_Mountain_Road_Bridge_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Mountain_Road_Bridge(sunset).png"
image bg_Mountain_Road_Bridge_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Mountain_Road_Bridge(night).png"#完成
image bg_In_front_of_the_mountain_road_bridge_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/In_front_of_the_mountain_road_bridge(noon).png"#山道桥之前路
image bg_In_front_of_the_mountain_road_bridge_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/In_front_of_the_mountain_road_bridge(sunset).png"
image bg_In_front_of_the_mountain_road_bridge_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/In_front_of_the_mountain_road_bridge(night).png"
image bg_Under_the_bed_in_the_room_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Under_the_bed_in_the_room(noon).png"#旅馆房间床下
image bg_Under_the_bed_in_the_room_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Under_the_bed_in_the_room(sunset).png"
image bg_Under_the_bed_in_the_room_light_on_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Under_the_bed_in_the_room_light_on(night).png"
image bg_Under_the_bed_in_the_room_light_off_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Under_the_bed_in_the_room_light_off(night).png"
image bg_Ceiling_of_the_room_night_light_on = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Ceiling_of_the_room_light_on(night).png"#房间床看天花板
image bg_Ceiling_of_the_room_night_light_off = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Ceiling_of_the_room_light_off(night).png"
image bg_Ceiling_of_the_room_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Ceiling_of_the_room(noon).png"
image bg_Ceiling_of_the_room_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Ceiling_of_the_room(sunset).png"
image bg_The_hotel_ping_pong_table_light_on = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/The_hotel_ping_pong_table_light_on.png"#旅馆兵乓球桌
image bg_The_hotel_ping_pong_table_light_off = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/The_hotel_ping_pong_table_light_off.png"
image bg_Rural_community_center_night_light_on = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Rural_community_center_light_on(night).png"#旅馆外表
image bg_Rural_community_center_night_light_off = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Rural_community_center_light_off(night).png"
image bg_Rural_community_center_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Rural_community_center(noon).png"
image bg_Rural_community_center_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Rural_community_center(sunset).png"
image Inside_the_hotel_room_light_on = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Inside_the_hotel_room_light_on(night).png"#旅馆房间内
image Inside_the_hotel_room_light_off = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Inside_the_hotel_room_light_off(night).png"
image Inside_the_hotel_room_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Inside_the_hotel_room(noon).png"
image Inside_the_hotel_room_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Inside_the_hotel_room(sunset).png"
image Rural_Backyard_night_light_on = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Rural_Backyard__light_on(night).png"
image Rural_Backyard_night_light_off = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Rural_Backyard_light_off(night).png"#旅馆后院
image Rural_Backyard_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Rural_Backyard(noon).png"
image Rural_Backyard_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Rural_Backyard(sunset).png"
image Rural_Bathroom_night_light_on = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Rural_Bathroom_light_on(night).png"
image Rural_Bathroom_night_light_off = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Rural_Bathroom_light_off(night).png"#旅馆浴室
image Rural_Bathroom_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Rural_Bathroom(noon).png"
image Rural_Bathroom_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_beach/Rural_Bathroom(sunset).png"

#map
image map_LADL = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_map/map.jpg"


#city
image bg_city_sky_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/sky(noon).png"#过场用
image bg_city_sky_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_cityh/sky(sunset).png"#过场用
image bg_city_sky_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/sky(night).png"#过场用
image bg_underground_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Underground_passage(noon).png"
image bg_underground_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Underground_passage(sunset).png"
image bg_underground_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Underground_passage(night).png"
image bg_street1_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Street1(noon).png"
image bg_street1_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Street1(sunset).png"
image bg_street1_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Street1(night).png"
image bg_street2_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Street2(noon).png"
image bg_street2_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Street2(sunset).png"
image bg_street2_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Street2(night).png"
image bg_street3_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Street3(noon).png"
image bg_street3_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Street3(sunset).png"
image bg_street3_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Street3(night).png"
image bg_police_station_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/police_station(noon).png"
image bg_police_station_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/police_station(sunset).png"
image bg_police_station_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/police_station(night).png"
image bg_park1_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/park1(noon).png"
image bg_park1_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/park1(sunset).png"
image bg_park1_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/park1(night).png"
image bg_park2_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/park2(noon).png"
image bg_park2_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/park2(sunset).png"
image bg_park2_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/park2(night).png"
image bg_park3_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/park3(noon).png"
image bg_park3_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/park3(sunset).png"
image bg_park3_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/park3(night).png"
image bg_Park_lawn_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Park_lawn(noon).png"
image bg_Park_lawn_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Park_lawn(sunset).png"
image bg_Park_lawn_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Park_lawn(night).png"
image bg_fishing_spot_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/fishing_spot(noon).png"
image bg_fishing_spot_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/fishing_spot(sunset).png"
image bg_fishing_spot_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/fishing_spot(night).png"
image bg_Restaurant_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Restaurant(noon).png"
image bg_Restaurant_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Restaurant(sunset).png"
image bg_Restaurant_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/Restaurant(night).png"
image bg_shopping_street_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/shopping_street(noon).png"
image bg_shopping_street_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/shopping_street(sunset).png"
image bg_shopping_street_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/shopping_street(night).png"
image bg_shopping_mall_seats_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/shopping_mall_seats.png"#接商店街
image bg_vacant_lot_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/vacant_lot(noon).png"
image bg_vacant_lot_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/vacant_lot(sunset).png"
image bg_vacant_lot_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/vacant_lot(night).png"
image bg_spa_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/spa(noon).png"
image bg_spa_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/spa(sunset).png"
image bg_spa_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/spa(night).png"

#???
image bg_prairie_noon = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/the_prairie_of dreams(noon).png"
image bg_prairie_sunset = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/the_prairie_of dreams(sunset).png"
image bg_prairie_night = "Submods/Literature_and_Daily_Life/L&DL_date/L&DL_date_bg/L&DL_city/the_prairie_of dreams(night).png"
